import Foundation
@main struct AutomaticSessionTests {
    static func main() throws {
        var checks = 0
        func check(_ condition: @autoclosure () -> Bool, _ message: String) {
            checks += 1; if !condition() { fputs("FAIL: \(message)\n", stderr); exit(1) }
        }
        var calendar = Calendar(identifier: .gregorian); calendar.timeZone = TimeZone(secondsFromGMT: 0)!
        let start = calendar.date(from: DateComponents(year: 2026, month: 9, day: 20, hour: 12))!
        func r(_ seconds: Double, _ percent: Double? = 80, _ connected: Bool = false, asleep: Bool = false, presence: HomePresence = .unknown) -> SessionReading {
            SessionReading(date: start.addingTimeInterval(seconds), percent: percent, connected: connected, asleep: asleep, presence: presence)
        }
        var tracker = AutomaticSessionTracker(hardware: "fixture")
        tracker.ingest(r(0, 80, true), calendar: calendar)
        tracker.ingest(r(30, 80, true), calendar: calendar)
        check(tracker.archive.active == nil, "Connected power, including optimized-charge hold, is not an outing")
        tracker.ingest(r(60), calendar: calendar)
        check(tracker.archive.active?.trigger == "unplugged", "Native disconnect starts automatically")
        let id = tracker.archive.active!.id
        tracker.ingest(r(90, 79, presence: .home), departed: true, calendar: calendar)
        check(tracker.archive.active?.id == id && tracker.archive.active?.leftHome == true, "Location departure merges into the power session")
        tracker.ingest(r(120, 78, presence: .home), calendar: calendar)
        check(tracker.archive.active?.minutes == 1 && tracker.archive.active?.drop == 2, "Only actual consecutive readings accumulate")
        check(tracker.archive.active?.days[0].homeMinutes == 0.5 && tracker.archive.active?.days[0].unknownMinutes == 0.5, "Mixed location endpoints are unknown")
        tracker.ingest(r(120, 10), calendar: calendar)
        check(tracker.archive.active?.drop == 2, "Duplicate timestamps cannot double-count")
        tracker.ingest(r(150, 79), calendar: calendar)
        tracker.ingest(r(180, 78), calendar: calendar)
        check(tracker.archive.active?.drop == 2, "Percentage rebound is not counted twice")
        tracker.ingest(r(210, 78, true), calendar: calendar)
        tracker.ingest(r(240, 78), calendar: calendar)
        check(tracker.archive.active?.id == id && tracker.archive.completed.isEmpty, "Brief charger bounce keeps one session")
        tracker.ingest(r(270, 77), calendar: calendar)
        tracker.ingest(r(300, 77, true), calendar: calendar)
        tracker.ingest(r(330, 78, true), calendar: calendar)
        check(tracker.archive.active != nil, "Connection debounce lasts a minute")
        tracker.ingest(r(360, 79, true), calendar: calendar)
        check(tracker.archive.active == nil && tracker.archive.completed.count == 1, "Stable connection closes automatically")
        check(tracker.archive.completed[0].endedAt == r(300).date && tracker.archive.completed[0].drop == 3, "Charge increase is excluded; closes at first connected reading")
        tracker.ingest(r(390, 80), calendar: calendar)
        check(tracker.archive.active?.id != id, "Next disconnect starts a new session")
        var initial = AutomaticSessionTracker(hardware: "fixture")
        initial.ingest(r(0), calendar: calendar)
        check(initial.archive.active?.trigger == "detected", "Already-unplugged launch doesn't invent exact departure")
        initial.ingest(r(30, 79), calendar: calendar)
        initial.interrupt()
        initial.ingest(r(7200, 60), calendar: calendar)
        initial.ingest(r(7230, 59), calendar: calendar)
        check(initial.archive.active?.minutes == 1 && initial.archive.active?.drop == 2, "Sleep and missing app time/discharge are excluded")
        let encoded = try JSONEncoder().encode(initial.archive)
        let decoded = try JSONDecoder().decode(SessionArchive.self, from: encoded)
        var restarted = AutomaticSessionTracker(hardware: "fixture", saved: decoded)
        restarted.ingest(r(15000, 40), calendar: calendar)
        restarted.ingest(r(15030, 39), calendar: calendar)
        check(restarted.archive.active?.id == initial.archive.active?.id, "Restart resumes the same session automatically")
        check(restarted.archive.active?.minutes == 1.5 && restarted.archive.active?.drop == 3 && restarted.archive.active?.interrupted == true, "Restart gap doesn't fabricate usage")
        check(AutomaticSessionTracker(hardware: "other", saved: decoded).archive.active == nil, "Hardware-specific statistics")
        var unknown = AutomaticSessionTracker(hardware: "fixture")
        unknown.ingest(r(0, nil), calendar: calendar)
        check(unknown.archive.active == nil, "Missing battery doesn't trigger scanning")
        unknown.ingest(r(30, .nan), calendar: calendar)
        check(unknown.archive.active == nil, "Invalid battery rejected")
        unknown.ingest(r(60), calendar: calendar)
        unknown.ingest(r(3600, 60), calendar: calendar)
        check(unknown.archive.active?.minutes == 0 && unknown.archive.active?.drop == 0, "Timer gaps cannot become hours of fake use")
        unknown.ingest(r(3630, 59, asleep: true), calendar: calendar)
        unknown.ingest(r(5000, 50), calendar: calendar)
        check(unknown.archive.active?.drop == 0, "Asleep readings excluded")
        unknown.stop(at: r(5000).date)
        check(unknown.archive.active == nil && unknown.archive.completed.isEmpty, "Turning learning off closes and discards empty session")
        unknown.ingest(r(8000), calendar: calendar)
        check(unknown.archive.active != nil, "Re-enabling learns without needing a new disconnect")
        var home = AutomaticSessionTracker(hardware: "fixture")
        home.ingest(r(0, 80, true), departed: true, calendar: calendar)
        check(home.archive.active?.trigger == "home", "Confirmed home departure can start while externally powered")
        home.ingest(r(30, 80, true), calendar: calendar)
        home.ingest(r(60, 80, true), calendar: calendar)
        check(home.archive.active == nil && home.archive.completed.isEmpty, "No fabricated consumption when leaving with external power")
        var gate = HomeTransitionGate()
        check(!gate.ingest(.away, fix: r(0).date, now: r(0).date), "Starting away does not prove departure from home")
        check(!gate.ingest(.home, fix: r(30).date, now: r(30).date), "Home arms detection")
        check(!gate.ingest(.away, fix: r(60).date, now: r(60).date), "One outside fix is insufficient")
        check(!gate.ingest(.away, fix: r(60).date, now: r(300).date), "Reusing the same location doesn't confirm departure")
        check(gate.ingest(.away, fix: r(180).date, now: r(180).date), "Two accurate outside fixes confirm departure")
        check(!gate.ingest(.away, fix: r(360).date, now: r(360).date), "One event per departure")
        _ = gate.ingest(.home, fix: r(390).date, now: r(390).date)
        _ = gate.ingest(.away, fix: r(420).date, now: r(420).date)
        check(gate.ingest(.away, fix: r(540).date, now: r(540).date), "Data detection has no notification cooldown")
        _ = gate.ingest(.home, fix: r(570).date, now: r(570).date)
        _ = gate.ingest(.away, fix: r(600).date, now: r(600).date)
        _ = gate.ingest(.unknown, fix: r(630).date, now: r(630).date)
        check(!gate.ingest(.away, fix: r(800).date, now: r(800).date), "Uncertain fix resets outside confirmation")
        check(!gate.ingest(.away, fix: r(900).date, now: r(1600).date), "Stale fix cannot confirm")
        let midnight = calendar.startOfDay(for: start)
        var split = AutomaticSessionTracker(hardware: "fixture")
        split.ingest(SessionReading(date: midnight.addingTimeInterval(-30), percent: 80, connected: false), calendar: calendar)
        split.ingest(SessionReading(date: midnight.addingTimeInterval(30), percent: 79, connected: false), calendar: calendar)
        check(split.archive.active?.days.count == 2 && split.archive.active?.days[0].minutes == 0.5 && split.archive.active?.days[1].drop == 0.5, "Midnight intervals split without double-counting")
        let week = WeeklyStatistics(archive: split.archive, now: start, calendar: calendar)
        check(week.days.count == 7 && week.minutes == 1 && !week.enoughForPattern, "Rolling week includes today with honest sparse-data state")
        let earlier = calendar.date(byAdding: .day, value: -9, to: midnight)!
        let session = AutomaticSession(startedAt: earlier, lastSeen: start, endedAt: start, trigger: "fixture", days: [BatteryDay(day: earlier, minutes: 90, drop: 15), BatteryDay(day: midnight, minutes: 30, drop: 5)])
        let windows = WeeklyStatistics(archive: SessionArchive(hardware: "fixture", completed: [session]), now: start, calendar: calendar)
        check(windows.minutes == 30 && windows.priorMinutes == 90, "Weekly boundaries use daily aggregates even across long sessions")
        check(windows.observedDays == 1 && !windows.enoughForPattern, "Large single session doesn't imply multi-day habits")
        var dst = calendar; dst.timeZone = TimeZone(identifier: "America/Santiago")!
        let dstDate = dst.date(from: DateComponents(year: 2026, month: 9, day: 9, hour: 12))!
        let dstWeek = WeeklyStatistics(archive: SessionArchive(hardware: "fixture"), now: dstDate, calendar: dst)
        check(dstWeek.days.count == 7 && Set(dstWeek.days.map { dst.component(.day, from: $0.day) }).count == 7, "Calendar days survive Santiago daylight-saving transition")
        print("PASS: \(checks) automatic lifecycle, sleep/restart, charger debounce, percentage noise, home transition and weekly statistics checks")
    }
}
